spring:
  thymeleaf:
    cache: false

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-auth-server
  redis:
    host: 192.168.23.134
    port: 6379
  session:
    store-type: redis

server:
  port: 20000

