spring:
  redis:
    host: 192.168.23.134
    port: 6379

  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.23.134:8848
  rabbitmq:
    host: 192.168.23.134
    virtual-host: /

  session:
    store-type: redis
  thymeleaf:
    cache: false



server:
  port: 25000
