spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.23.134:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
       server-addr: 127.0.0.1:8848

  application:
    name: gulimall-order

  thymeleaf:
    cache: false

  session:
    store-type: redis

  redis:
    host: 192.168.23.134
    port: 6379
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  transaction:
    rollback-on-commit-failure: true


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto         #ID自增


server:
  port: 9000


gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
